apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  namespace: app-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      securityContext:
            fsGroup: 1000 
            runAsUser: 1000
      containers:
        - name: app
          image: hamo139/nodejs:latest
          ports:
            - name: httpport
              containerPort: 3000
         
